local utils = require("utils")

utils.nmap_leader("a", "<cmd>Alpha<CR>", "Alpha")
utils.nmap_leader("w", "<cmd>w<CR>", "Save")
utils.nmap_leader("q", "<cmd>q<CR>", "Quit")
utils.nmap_leader("h", "<cmd>nohlsearch<CR>", "No Highlight")
utils.nmap_leader("u", "<cmd>undo<CR>", "Undo")
utils.nmap_leader("r", "<cmd>redo<CR>", "Redo")
utils.nmap_leader("L", "<cmd>Lazy<CR>", "Lazy")
utils.nmap_leader("=", "<cmd>vertical resize +5<CR>", "Resize +5")
utils.nmap_leader("-", "<cmd>vertical resize -5<CR>", "Resize -5")
utils.nmap_leader("v", "<C-W>v", "Split Right")
utils.nmap_leader("V", "<C-W>s", "Split Below")
utils.nmap_leader("q", "<cmd>q<CR>", "Close Window")
