[[shades]]
name = "blue-light-filter"
start_time = 17:00:00
# end_time = 06:00:00
[shaders.config]
temperature = 1500.0
strength = 0.5

[[shades]]
name = "grayscale"
start_time = 23:00:00
end_time = 03:00:00
