general:
  focus_follows_cursor: true

  toggle_workspace_on_refocus: false

  cursor_jump:
    enabled: true 

    trigger: "window_focus"

gaps:
  inner_gap: "0px"

  outer_gap:
    top: "0px"
    right: "0px"
    bottom: "0px"
    left: "0px"

window_effects:
  focused_window:
    border:
      enabled: true

    hide_title_bar:
      enabled: true
  
    corner_style:
      enabled: true 
      style: "square"
     
  other_windows:
    border:
      enabled: false 
     
    hide_title_bar:
      enabled: true
   
    corner_style:
      enabled: true 
      style: "square"

    transparency:
      enabled: true
      opacity: "80%"

window_behavior:
  initial_state: "tiling"

  state_defaults:
    floating:
      centered: true

      shown_on_top: true 

    fullscreen:
      maximized: true

workspaces:
  - name: "1"
  - name: "2"
  - name: "3"
  - name: "4"
  - name: "5"
  - name: "6"
  - name: "7"
  - name: "8"
  - name: "9"

window_rules:
  - commands: ["ignore"]
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: "zebar" }

      # Ignores the Command Palette
      - window_class: { equals: "WinUIDesktopWin32WindowClass" }
        window_title: { equals: "Command Palette" }

      # Ignores picture-in-picture windows for browsers.
      - window_title: { regex: "[Pp]icture.in.[Pp]icture" }
        window_class: { regex: "Chrome_WidgetWin_1|MozillaDialogClass" }

binding_modes:
  # When enabled, the focused window can be resized via WASD.
  - name: "resize"
    keybindings:
      - commands: ["resize --width -2%"]
        bindings: ["h", "left"]
      - commands: ["resize --width +2%"]
        bindings: ["l", "right"]
      - commands: ["resize --height +2%"]
        bindings: ["k", "up"]
      - commands: ["resize --height -2%"]
        bindings: ["j", "down"]
      # Press enter/escape to return to default keybindings.
      - commands: ["wm-disable-binding-mode --name resize"]
        bindings: ["escape", "enter"]

  # When enabled, all keybindings are disabled except for alt+shift+p which
  # returns to default keybindings.
  - name: "pause"
    keybindings:
      - commands: ["wm-disable-binding-mode --name pause"]
        bindings: ["alt+shift+p"]

keybindings:
  # Shift focus in a given direction.
  - commands: ["focus --direction left"]
    bindings: ["rwin+h"]
  - commands: ["focus --direction right"]
    bindings: ["rwin+l"]
  - commands: ["focus --direction up"]
    bindings: ["rwin+k"]
  - commands: ["focus --direction down"]
    bindings: ["rwin+j"]

  # Move focused window in a given direction.
  - commands: ["move --direction left"]
    bindings: ["rwin+shift+h"]
  - commands: ["move --direction right"]
    bindings: ["rwin+shift+l"]
  - commands: ["move --direction up"]
    bindings: ["rwin+shift+k"]
  - commands: ["move --direction down"]
    bindings: ["rwin+shift+j"]

  # resizing via wasd. The binding mode is defined above with
  # the name "resize".
  - commands: ["wm-enable-binding-mode --name resize"]
    bindings: ["rwin+shift+r"]

  # Disables all keybindings until alt+shift+p is pressed again.
  - commands: ["wm-enable-binding-mode --name pause"]
    bindings: ["alt+shift+p"]

  # Change tiling direction. This determines where new tiling windows will
  # be inserted.
  - commands: ["toggle-tiling-direction"]
    bindings: ["alt+v"]

  # Change focus from tiling windows -> floating -> fullscreen.
  - commands: ["wm-cycle-focus"]
    bindings: ["rwin+alt+y"]

  # Change the focused window to be floating.
  - commands: ["toggle-floating --centered"]
    bindings: ["rwin+shift+y"]

  # Change the focused window to be tiling.
  - commands: ["toggle-tiling"]
    bindings: ["rwin+y"]

  # Change the focused window to be fullscreen.
  - commands: ["toggle-fullscreen"]
    bindings: ["rwin+ctrl+y"]

  # Minimize rocused window.
  - commands: ["toggle-minimized"]
    bindings: ["alt+m"]

  - commands: ["close"]
    bindings: ["rwin+q"]

  # Re-evaluate configuration file.
  - commands: ["wm-reload-config"]
    bindings: ["rwin+shift+q"]

  # Redraw all windows.
  - commands: ["wm-redraw"]
    bindings: ["alt+shift+w"]

  # Focus the next/previous workspace defined in `workspaces` config.
  - commands: ["focus --next-workspace"]
    bindings: ["rwin+ctrl+right"]
  - commands: ["focus --prev-workspace"]
    bindings: ["rwin+ctrl+left"]
  - commands: ["focus --next-workspace"]
    bindings: ["ctrl+alt+shift+d"]
  - commands: ["focus --prev-workspace"]
    bindings: ["ctrl+alt+shift+a"]

  # Focus the workspace that last had focus.
  - commands: ["focus --recent-workspace"]
    bindings: ["rwin+z"]

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ["focus --workspace 1"]
    bindings: ["rwin+1"]
  - commands: ["focus --workspace 2"]
    bindings: ["rwin+2"]
  - commands: ["focus --workspace 3"]
    bindings: ["rwin+3"]
  - commands: ["focus --workspace 4"]
    bindings: ["rwin+4"]
  - commands: ["focus --workspace 5"]
    bindings: ["rwin+5"]
  - commands: ["focus --workspace 6"]
    bindings: ["rwin+6"]
  - commands: ["focus --workspace 7"]
    bindings: ["rwin+7"]
  - commands: ["focus --workspace 8"]
    bindings: ["rwin+8"]
  - commands: ["focus --workspace 9"]
    bindings: ["rwin+9"]

  # Move the focused window's parent workspace to a monitor in a given
  # direction.
  - commands: ["move-workspace --direction left"]
    bindings: ["rwin+ctrl+shift+h"]
  - commands: ["move-workspace --direction right"]
    bindings: ["rwin+ctrl+shift+l"]
  - commands: ["move-workspace --direction up"]
    bindings: ["rwin+ctrl+shift+k"]
  - commands: ["move-workspace --direction down"]
    bindings: ["rwin+ctrl+shift+j"]

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ["move --workspace 1", "focus --workspace 1"]
    bindings: ["rwin+shift+1"]
  - commands: ["move --workspace 2", "focus --workspace 2"]
    bindings: ["rwin+shift+2"]
  - commands: ["move --workspace 3", "focus --workspace 3"]
    bindings: ["rwin+shift+3"]
  - commands: ["move --workspace 4", "focus --workspace 4"]
    bindings: ["rwin+shift+4"]
  - commands: ["move --workspace 5", "focus --workspace 5"]
    bindings: ["rwin+shift+5"]
  - commands: ["move --workspace 6", "focus --workspace 6"]
    bindings: ["rwin+shift+6"]
  - commands: ["move --workspace 7", "focus --workspace 7"]
    bindings: ["rwin+shift+7"]
  - commands: ["move --workspace 8", "focus --workspace 8"]
    bindings: ["rwin+shift+8"]
  - commands: ["move --workspace 9", "focus --workspace 9"]
    bindings: ["rwin+shift+9"]
  
  # Launch CMD terminal. Alternatively, use `shell-exec --command wt` or
  # `shell-exec --command %ProgramFiles%/Git/git-bash.exe` to start Windows
  # Terminal and Git Bash respectively.
  # - commands: ["shell-exec --command wt"]
    # bindings: ["rwin+enter"]
  # Custom Apps
  # - commands: ["shell-exec wezterm-gui"]
  #   bindings: ["rwin+enter"]
