[general]
import = [
  "C:\\Users\\Ashwin\\AppData\\Local\\npm-cache\\_npx\\808b709e6234a442\\node_modules\\alacritty-themes\\themes\\Tokyonight_Night.toml"
]

[terminal]
shell = { program = "C:\\Users\\Ashwin\\AppData\\Local\\Microsoft\\WindowsApps\\Microsoft.PowerShell_8wekyb3d8bbwe\\pwsh.exe", args = ["-NoExit", "-WorkingDirectory", "~", "-NoProfileLoadTime", "-NoLogo"] }

[window]
dynamic_title = false
# decorations = "None"
opacity = 0.7
  [window.padding]
  x = 7
  y = 7

[font]
size = 12
  [font.normal]
  family = "MonoLisa, Cascadia Code NF"
  style = "Regular"

  [font.bold]
  family = "MonoLisa, Cascadia Code NF"
  style = "Bold"

  [font.italic]
  family = "MonoLisa, Cascadia Code NF"
  style = "Italic"
