#!/usr/bin/env bash

HOSTS="/etc/hosts"

DOMAINS=(
  "youtube.com"
  "www.youtube.com"
  "m.youtube.com"
  "youtu.be"
  "music.youtube.com"
  "gaming.youtube.com"
  "discord.com"
)

for domain in "${DOMAINS[@]}"; do
  if ! grep -q "$domain" "$HOSTS"; then
    echo "0.0.0.0 $domain" | sudo tee -a "$HOSTS" > /dev/null
  fi
done

sudo systemctl restart NetworkManager

echo "Focus Mode On."
